version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magwegwe-sda-web
    restart: unless-stopped
    ports:
      - "3005:80"
    environment:
      - NODE_ENV=production
